server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: oauth2-gateway
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/skin
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: # 配置路由路径
        - id: business-demo-route
          uri: lb://business-demo
          predicates:
            - Path=/business-demo/**
          filters:
            - StripPrefix=1
        - id: business-resource
          uri: lb://business-resource
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
        - id: business-menu-route
          uri: lb://business-menu
          predicates:
            - Path=/business-menu/**
          filters:
            - StripPrefix=1
        - id: oauth2-auth-route
          uri: lb://oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: oauth2-auth-login
          uri: lb://oauth2-auth
          predicates:
            - Path=/login
          filters:
            - PreserveHostHeader
        - id: oauth2-auth-token
          uri: lb://oauth2-auth
          predicates:
            - Path=/oauth/token
          filters:
            - PreserveHostHeader
        - id: oauth2-auth-authorize
          uri: lb://oauth2-auth
          predicates:
            - Path=/oauth/authorize
          filters:
            - PreserveHostHeader
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true # 使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' # 配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password: root
    cache-minute: 1

secure:
  ignore:
    urls: # 配置白名单路径
      - "/actuator/**"
      - "/oauth/token"
      - "/oauth/authorize"
      - "/login"
      - "/resource/demo"
